plugins {
    id 'java'
}

group = 'org.example'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = "21"
    targetCompatibility = "21"
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

sourceSets {
    main.java.srcDirs += 'src/main/java'
    main.resources.srcDirs += 'src/main/resources'
    test.java.srcDirs += 'src/test/java'
    test.resources.srcDirs += 'src/test/resources'
}

test {
    // Enable JUnit 5 (Gradle 4.6+).
    useJUnitPlatform()
    dependsOn 'cleanTest'
    testLogging {
        events "passed", "skipped", "failed"
    }
}